### ISSUE TITLE
MessageCommand arg parsing not passing args correctly

### ISSUE THREAD

**Issue by Jonxslays** [Cursed-Solutions/Tanjun#200]
I updated Tanjun this morning and realized some of my message commands were not working.
Am I misusing something, or is this a bug?

Reproduction:
```py
import os

import hikari
import tanjun
from dotenv import load_dotenv

load_dotenv()


async def prefix_getter(_: tanjun.abc.MessageContext) -> tuple[str]:
    return ("$",)

bot = hikari.GatewayBot(os.environ["TOKEN"])
client = (
    tanjun.Client.from_gateway_bot(bot, mention_prefix=True)
    .set_prefix_getter(prefix_getter)
)

component = tanjun.Component()
client.add_component(component)

@component.with_command
@tanjun.with_greedy_argument("value")
@tanjun.with_argument("name")
@tanjun.with_parser
@tanjun.as_message_command("test")
async def test_command(ctx: tanjun.abc.MessageContext, name: str, value: str) -> None:
    await ctx.respond(f"name was {name!r}, value was {value!r}.")

bot.run()
```

with Tanjun version 2.3.0a1:
Bot responds as expected.

with Tanjun version 2.3.1a1:
```bash
Traceback (most recent call last):
  File "/home/jonx/projects/tanjun-test/.venv/lib/python3.10/site-packages/tanjun/clients.py", line 2075, in on_message_create_event
    if await component.execute_message(ctx, hooks=hooks):
  File "/home/jonx/projects/tanjun-test/.venv/lib/python3.10/site-packages/tanjun/components.py", line 1017, in execute_message
    await command.execute(ctx, hooks=hooks)
  File "/home/jonx/projects/tanjun-test/.venv/lib/python3.10/site-packages/tanjun/commands.py", line 2304, in execute
    await self._callback.resolve_with_command_context(ctx, ctx, **kwargs)
  File "/home/jonx/projects/tanjun-test/.venv/lib/python3.10/site-packages/tanjun/injecting.py", line 489, in resolve
    result = self._callback(*args, **sub_results, **kwargs)
TypeError: test_command() missing 1 required positional argument: 'value'
```

**Comment by sudoBash418** [comment]
This is more of a workaround, but I found that switching away from decorators fixed the problem for me.

This results in a `TypeError` being thrown: `TypeError: my_command() missing 1 required positional argument: 'ctx'`:
```python
@tanjun.as_slash_command("mycmd", "description", default_to_ephemeral=True)
async def my_command(self, ctx: tanjun.context.SlashContext, user: Optional[hikari.User] = None):
    # logic here

component.add_slash_command(my_command)
```

Whereas this works fine:
```python
async def my_command_inner(self, ctx: tanjun.context.SlashContext, user: Optional[hikari.User] = None):
    # logic here

my_command = tanjun.SlashCommand(my_command_inner, "mycmd", "description", default_to_ephemeral=True)
component.add_slash_command(my_command)
```

**Comment by FasterSpeeding** [comment]
This should be fixed in the latest release
